version: "2.4"

volumes:
  keycloak-db: { }

services:

  api:
    image: ghcr.io/noumenadigital/seed/api:latest
    build:
      context: api
    ports:
      - "8080:8080"
      - "8000:8000"
      - "8888:8888"
    environment:
      KEYCLOAK_URL: http://keycloak:11000
      ENGINE_URL: http://engine:12000
      READ_MODEL_URL: http://read-model:15000
      HTTP_PORT: 8080
      HTTP_ADMIN_PORT: 8000
      # JVM remote debug
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888
      DEBUG_REQUEST_RESPONSE: "true"
      API_SERVER_URL: ${API_SERVER_URL:-http://localhost:8080}
    healthcheck:
      test: "curl -s -f http://localhost:8000/health || exit 1"
      interval: 1s
      retries: 100
    depends_on:
      keycloak-provisioning:
        condition: service_started
      engine:
        condition: service_healthy

  engine:
    image: ghcr.io/noumenadigital/seed/engine:latest
    build:
      context: npl
    ports:
      - "12000:12000"
    environment:
      ENGINE_AUTH_SERVER_BASE_URL: http://keycloak:11000
      ENGINE_DB_URL: "jdbc:postgresql://engine-db:5432/engine"
      ENGINE_DB_USER: seed
      ENGINE_DB_PASSWORD: secret
      ENGINE_DB_HISTORY_USER: history
      ENGINE_DB_HISTORY_PASSWORD: secret
      ENGINE_DB_HISTORY_SCHEMA: history
      POSTGRAPHILE_DB_USER: postgraphile
      POSTGRAPHILE_DB_PASSWORD: postgraphile
    healthcheck:
      # add basic port opened check since image doesn't provide any tools to do a better check
      test: /bin/bash -c '/usr/bin/printf "GET / HTTP/1.1\r\nHost\:engine:12000\r\n\r\n" > /dev/tcp/127.0.0.1/12000'
      interval: 1s
      retries: 60
    depends_on:
      engine-db:
        condition: service_started
      keycloak:
        condition: service_healthy

  history:
    image: ghcr.io/noumenadigital/packages/history:2022.1.71
    ports:
      - "12010:12010"
      - "12711:12711"
    environment:
      HISTORY_ADMIN_HOST: 0.0.0.0
      HISTORY_ADMIN_PORT: 12711
      HISTORY_DB_URL: "jdbc:postgresql://engine-db:5432/engine"
      HISTORY_DB_USER: history
      HISTORY_DB_PASSWORD: secret
      HISTORY_DB_SCHEMA: history
      HISTORY_DB_ENGINE_SCHEMA: noumena
      HISTORY_STARTUP_HEALTH_CHECK_ATTEMPTS: 10
    depends_on:
      engine-db:
        condition: service_started
      engine:
        condition: service_healthy

  read-model:
    image: ghcr.io/noumenadigital/packages/postgraphile:2022.1.71
    ports:
      - "15000:15000"
    environment:
      DATABASE_URL: postgres://seed:secret@engine-db:5432/engine
      POSTGRAPHILE_DB_USER: postgraphile
      TRUSTED_ISSUERS: "http://keycloak:11000/**,"
      ENGINE_HEALTH_ENDPOINT: "http://engine:12000/actuator/health"
      ENGINE_TIMEOUT_SECONDS: 250
      SCHEMA: noumena
      PORT: 15000
    depends_on:
      engine-db:
        condition: service_started
      keycloak:
        condition: service_healthy

  engine-db:
    image: postgres:14.4-alpine
    command: postgres -c log_statement=all
    mem_limit: 256m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: engine
      POSTGRES_USER: seed
      POSTGRES_PASSWORD: secret
      HISTORY_DB_USER: history
      HISTORY_DB_PASSWORD: secret
    volumes:
      - ./db_init/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh

  keycloak-provisioning:
    image: ghcr.io/noumenadigital/seed/keycloak-provisioning:latest
    build:
      context: keycloak-provisioning
    command: /local.sh
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.0
    command: start --hostname-strict=false --hostname-strict-https=false --health-enabled=true --http-enabled=true --metrics-enabled=true --db=postgres
    ports:
      - "11000:11000"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Seed123!
      KC_DB_URL: jdbc:postgresql://keycloak-db/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: testing
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 11000
      KC_HOSTNAME: keycloak
    healthcheck:
      test: curl -s localhost:11000/health || exit 1
      interval: 1s
      retries: 60
    depends_on:
      keycloak-db:
        condition: service_started

  keycloak-db:
    image: postgres:14.4-alpine
    mem_limit: 256m
    ports:
      - "11040:5432"
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: testing

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
