name: Deploy on merge to master
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  MAVEN_REPO_USER: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_REPO_PASS: ${{ secrets.MAVEN_PASSWORD }}
  MAVEN_CLI_OPTS: -s .m2/settings.xml --batch-mode
  VERSION: '1.0.${{ github.run_number }}'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - run: |
          make -e integration-test

  images:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - run: |
          make -e images

  deploy:
    runs-on: "self-hosted"
    needs: "build"
    steps:
      - uses: actions/checkout@v3
      - run: |
          make -e deploy-dev 
