name: Build on PR
on: [pull_request]

env:
  MAVEN_REPO_USER: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_REPO_PASS: ${{ secrets.MAVEN_PASSWORD }}
  MAVEN_CLI_OPTS: -s .m2/settings.xml --batch-mode
  VERSION: '1.0.${{ github.run_number }}'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - run: |
          make -e integration-test
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
      - name: Scan Engine for Vulnerabilities
        uses: anchore/scan-action@v3
        with:
          image: ghcr.io/noumenadigital/seed/engine:latest
          fail-build: false
          output-format: table
      - name: Scan API for Vulnerabilities
        uses: anchore/scan-action@v3
        with:
          image: ghcr.io/noumenadigital/seed/api:latest
          fail-build: false
          output-format: table
