name: Build and deploy on merge to master
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  GITHUB_USER_NAME: ${{ secrets.GH_USERNAME }}
  GITHUB_USER_PASS: ${{ secrets.GH_PASSWORD }}
  MAVEN_CLI_OPTS: -s .m2/settings.xml --batch-mode
  VERSION: '1.0.${{ github.run_number }}'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PASSWORD }}
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - run: |
          make -e integration-test images
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

  deploy:
    runs-on: [self-hosted, seed-dev]
    needs: "build"
    steps:
      - uses: actions/checkout@v3
      - run: |
          make -e clean-dev
          make -e deploy-dev

  deploy-shared-dev:
    runs-on: [self-hosted, shared-dev]
    needs: "build"
    steps:
      - uses: actions/checkout@v3
      - run: |
          make -e clean-shared-dev
      - run: |
          make -e deploy-shared-dev
