name: Build and deploy on merge to master
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  MAVEN_REPO_USER: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_REPO_PASS: ${{ secrets.MAVEN_PASSWORD }}
  MAVEN_CLI_OPTS: -s .m2/settings.xml --batch-mode
  VERSION: '1.0.${{ github.run_number }}'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - run: |
          make -e integration-test
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

  images:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - run: |
          make -e images

  deploy:
    runs-on: [self-hosted, seed-dev]
    needs: "build"
    steps:
      - uses: actions/checkout@v3
      - run: |
          make -e clean-dev
          make -e deploy-dev

  deploy-shared-dev:
    runs-on: [self-hosted, shared-dev]
    needs: "build"
    steps:
      - uses: actions/checkout@v3
      - run: |
          make -e clean-shared-dev
          make -e deploy-shared-dev
